name: NetBSD

on:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
      - .gitignore
  pull_request:
    paths-ignore:
      - "**.md"
      - "**/LICENSE"
      - .github/FUNDING.yml
      - .editorconfig
      - .gitignore

jobs:
  check:
    name: NetBSD
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rust-src
        target: x86_64-unknown-netbsd
    - name: Cache cargo output
      uses: Swatinem/rust-cache@v2
    - name: Check NetBSD (x86_64)
      run: cargo check --target x86_64-unknown-netbsd
    - name: Check NetBSD (aarch64)
      run: cargo check --target aarch64-unknown-netbsd -Zbuild-std=core,alloc
